#!/usr/bin/env bash
set -euo pipefail

#
# Generate .env and docker/kong/kong.yml with fresh random secrets.
# Run once before your first `docker-compose up -d`.
#
# Prerequisites: openssl (ships with macOS and most Linux distros)
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_DIR}/.env"
KONG_TEMPLATE="${PROJECT_DIR}/docker/kong/kong.yml.template"
KONG_OUTPUT="${PROJECT_DIR}/docker/kong/kong.yml"

# ── helpers ──────────────────────────────────────────────────────────────────

base64url() {
  openssl enc -base64 -A | tr '+/' '-_' | tr -d '='
}

generate_jwt() {
  local secret="$1" role="$2"
  local iat exp header payload h p sig

  iat=$(date +%s)
  exp=$((iat + 10 * 365 * 24 * 3600))

  header='{"alg":"HS256","typ":"JWT"}'
  payload="{\"iss\":\"supabase\",\"role\":\"${role}\",\"iat\":${iat},\"exp\":${exp}}"

  h=$(printf '%s' "$header"  | base64url)
  p=$(printf '%s' "$payload" | base64url)
  sig=$(printf '%s' "${h}.${p}" \
    | openssl dgst -sha256 -hmac "$secret" -binary \
    | base64url)

  printf '%s.%s.%s' "$h" "$p" "$sig"
}

# ── guard ────────────────────────────────────────────────────────────────────

if [ -f "$ENV_FILE" ]; then
  printf '⚠  .env already exists at %s\n' "$ENV_FILE"
  read -rp "Overwrite? [y/N] " answer
  case "$answer" in
    [yY]*) ;;
    *)     echo "Aborted."; exit 0 ;;
  esac
fi

# ── generate secrets ─────────────────────────────────────────────────────────

echo "Generating secrets …"

POSTGRES_PASSWORD=$(openssl rand -hex 24)
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
ANON_KEY=$(generate_jwt "$JWT_SECRET" "anon")
SERVICE_ROLE_KEY=$(generate_jwt "$JWT_SECRET" "service_role")

# ── write .env ───────────────────────────────────────────────────────────────

cat > "$ENV_FILE" <<EOF
# Generated by scripts/generate-env.sh — do not commit this file.

# Postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}

# URLs (change these if you expose the app beyond localhost)
SUPABASE_PUBLIC_URL=http://localhost:8001
SITE_URL=http://localhost:3001
EOF

echo "✔  Wrote ${ENV_FILE}"

# ── generate kong.yml ────────────────────────────────────────────────────────

if [ -f "$KONG_TEMPLATE" ]; then
  sed \
    -e "s|__ANON_KEY__|${ANON_KEY}|g" \
    -e "s|__SERVICE_ROLE_KEY__|${SERVICE_ROLE_KEY}|g" \
    "$KONG_TEMPLATE" > "$KONG_OUTPUT"
  echo "✔  Wrote ${KONG_OUTPUT}"
else
  echo "⚠  Kong template not found at ${KONG_TEMPLATE} — skipping."
fi

echo ""
echo "Done. You can now run:"
echo "  docker-compose up -d"
echo "  ./seed-user.sh"
